[package]
name = "retrorecord"
version = "0.1.0"
authors = ["Ricky Miller <ricky.miller@gmail.com>"]

[dependencies]
notify = "4.0.0"
egg-mode = "0.12.0"
tokio-core = "0.1.11"
rand = "0.3"
mime = "0.3.5"
dialoguer = "0.1.0"
regex = "0.2"
clap = "2.31.1"
